# Generated by Django 4.2.1 on 2023-06-05 19:34

import datetime
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import foundation.models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(blank=True, max_length=150, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CurrencyMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_name', models.CharField(max_length=50, verbose_name='Currency Name')),
                ('currency_code', models.CharField(max_length=20, verbose_name='Currency Code')),
                ('currency_symbol', models.CharField(blank=True, max_length=5, null=True, verbose_name='Currency Symbol')),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
            ],
            options={
                'verbose_name': 'Currency Master',
                'verbose_name_plural': 'Currency Master',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'User Type',
                'verbose_name_plural': 'User Type',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number1', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Phone Number 1')),
                ('phone_number2', phonenumber_field.modelfields.PhoneNumberField(blank=True, help_text='For whats app', max_length=128, null=True, region=None, verbose_name='Phone Number 2')),
                ('base_currency', models.ForeignKey(default=foundation.models.CurrencyMaster.get_default_pk, on_delete=django.db.models.deletion.CASCADE, to='foundation.currencymaster', verbose_name='Base Currency')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinfo', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthenticationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('two_step_verification', models.BooleanField(default=False, verbose_name='Two Step Verification')),
                ('device_authenticator', models.BooleanField(default=False, verbose_name='Device Authenticator')),
                ('otp_verification', models.BooleanField(default=False, verbose_name='OTP Verification')),
                ('otp', models.CharField(blank=True, max_length=10, null=True, verbose_name='OTP')),
                ('otp_expired_at', models.DateTimeField(blank=True, null=True, verbose_name='Expired At')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userauth', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Buy Rate')),
                ('sell_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=10, verbose_name='Sell Rate')),
                ('effective_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='Effective Date')),
                ('currency_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curr_master_from', to='foundation.currencymaster', verbose_name='Currency From')),
                ('currency_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curr_master_to', to='foundation.currencymaster', verbose_name='Currency To')),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'verbose_name_plural': 'Currency Rate',
                'ordering': ('effective_date',),
                'get_latest_by': ('effective_date',),
            },
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='foundation.usertype', verbose_name='User Type'),
        ),
    ]
