# Generated by Django 4.2.1 on 2023-06-25 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('foundation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('slug', models.SlugField(editable=False, max_length=100, verbose_name='Slug')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='menu/icon/', verbose_name='Icon')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('order', models.IntegerField(default=0, verbose_name='Order')),
                ('visible_for_authenticated', models.BooleanField(default=True, verbose_name='Visible for authenticated')),
                ('visible_for_anonymous', models.BooleanField(default=False, verbose_name='Visible for anonymous')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menu',
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='MenuAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=10, unique=True, verbose_name='Action')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='menu_items/icon/', verbose_name='Icon')),
                ('class_name', models.CharField(blank=True, help_text='Use for HTML class name.', max_length=10, null=True, verbose_name='Class name')),
            ],
            options={
                'verbose_name': 'Menu Action',
                'verbose_name_plural': 'Menu Action',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='UserMenuSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Menu Security',
                'verbose_name_plural': 'User Menu Security',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='UsersMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Users Menu Permission',
                'verbose_name_plural': 'Users Menu Permission',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='UserTypeMenuPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Type Menu Permission',
                'verbose_name_plural': 'User Type Menu Permission',
                'ordering': ('-id',),
            },
        ),
        migrations.AlterModelOptions(
            name='usertype',
            options={'ordering': ('-id',), 'verbose_name': 'User Type', 'verbose_name_plural': 'User Type'},
        ),
        migrations.AddField(
            model_name='usertype',
            name='visible_in_signup',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertype',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Name'),
        ),
        migrations.AddConstraint(
            model_name='usertype',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_name'),
        ),
        migrations.AddField(
            model_name='usertypemenupermission',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.menu', verbose_name='Select menu'),
        ),
        migrations.AddField(
            model_name='usertypemenupermission',
            name='menu_action',
            field=models.ManyToManyField(related_name='user_type_menu_action_set', to='foundation.menuaction', verbose_name='Select menu actions'),
        ),
        migrations.AddField(
            model_name='usertypemenupermission',
            name='user_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usertype_menu_set', to='foundation.usertype', verbose_name='Select user type'),
        ),
        migrations.AddField(
            model_name='usersmenupermission',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foundation.menu', verbose_name='Select menu'),
        ),
        migrations.AddField(
            model_name='usersmenupermission',
            name='menu_action',
            field=models.ManyToManyField(related_name='user_menu_action_set', to='foundation.menuaction', verbose_name='Select menu actions'),
        ),
        migrations.AddField(
            model_name='usersmenupermission',
            name='users_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='users_menu_set', to='foundation.usermenusecurity', verbose_name='Select users'),
        ),
        migrations.AddField(
            model_name='usermenusecurity',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Select users'),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='foundation.menu', verbose_name='Parent'),
        ),
        migrations.AlterUniqueTogether(
            name='usertypemenupermission',
            unique_together={('user_type', 'menu')},
        ),
    ]
