# Generated by Django 4.2.1 on 2023-06-25 10:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "foundation",
            "0002_menu_menuaction_usermenusecurity_usersmenupermission_and_more",
        ),
    ]

    def insertDataToMenuAction(apps, schema_editor):
        MenuAction = apps.get_model("foundation", "MenuAction")
        MenuAction.objects.bulk_create(
            [
                MenuAction(action="add"),
                MenuAction(action="edit"),
                MenuAction(action="view"),
                MenuAction(action="delete"),
                MenuAction(action="print"),
                MenuAction(action="notify"),
                MenuAction(action="approval"),
            ]
        )

    operations = [
        migrations.RunPython(insertDataToMenuAction),
    ]
